# Generated by Django 4.2.9 on 2024-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='outstanding_debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
