# Generated by Django 4.2.9 on 2024-01-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
