# Generated by Django 4.2.9 on 2024-01-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_member_options_member_created_member_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='rent_fee_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
