# Generated by Django 4.2.9 on 2024-01-26 09:27

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_transaction_rent_fee_charged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
